field: 97b5ac09-89a5-45c7-97d0-60eab33770cd # Recipe Contents
fieldLayouts:
  78c4afb9-ed38-46c4-a524-adc31c44ff99:
    tabs:
      -
        elements:
          -
            fieldUid: c403b4ab-3b97-46c3-8739-01c0a619b47c # Steps Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a6c581b8-9017-426c-8dc4-3536bc4a5b38 # Steps Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a6c581b8-9017-426c-8dc4-3536bc4a5b38: # Steps Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: ''
    name: 'Steps Content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  c403b4ab-3b97-46c3-8739-01c0a619b47c: # Steps Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: ''
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
