fieldLayouts:
  caab5821-efc1-4ac2-a2e2-2cb1be71e340:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Drink Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: d009f680-1d1d-4eb3-ac80-72e4d1e89f49 # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7437c837-2418-4e22-9b5d-ad9f84fb3148 # Page Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Drink Details'
        sortOrder: 1
handle: default
hasTitleField: true
name: Default
section: d9e8a742-bf54-49e4-9b25-9feab611db7e # Drinks
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
