defaultPlacement: end
enableVersioning: true
handle: drinks
name: Drinks
propagationMethod: all
siteSettings:
  76448c4b-5e92-41aa-bfef-144fa20ddb13: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry
    uriFormat: 'drinks/{slug}'
type: channel
