defaultPlacement: end
enableVersioning: true
handle: recipes
name: Recipes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  76448c4b-5e92-41aa-bfef-144fa20ddb13: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry
    uriFormat: 'recipes/{slug}'
type: channel
